source "https://rubygems.org"
gem "sinatra"
gem "sinatra-advanced-routes", :require => "sinatra/advanced_routes"
gem "rufus-scheduler"
gem "configliere"
gem "sequel"
gem "rspec"
gem "sqlite3", :platform => [:ruby]
gem "system-getifaddrs"
gem "json"
gem "nokogiri"
